name: gradle-ci
on:
  push:
    branches:
      - main

jobs:
  publish:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: 18
          distribution: temurin
          cache: "gradle"
      - name: Publish with Gradle
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_SECRET: ${{ secrets.MAVEN_SECRET }}
        uses: gradle/gradle-build-action@v2
        with:
          arguments: "publish"